# Common docker stack config
version: '3.8'

networks:
  internal:
  web:
    # Override the network name.
    # When not external, it makes docker use this name instead of automatically created project-scoped version
    # We need the explicitliy named network for use with "traefik.docker.network" label
    name: web-public
    external: false # Do not expect external web network in developmet

volumes:
  dbdata:
  pgadmindata:

services:
  traefik:
    image: traefik:v2.4
    networks:
      - web

  db:
    image: postgres:13.2-alpine
    environment:
      POSTGRES_USER: postgres
    networks:
      - internal

  redis:
    image: redis:6.2.4-alpine
    command: redis-server --requirepass myRedisPwd
    networks:
      - internal

  api:
    networks:
      - web
      - internal
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
      PORT: 4000

  webclient:
    networks:
      - web
