version: '3.8'

services:
  api:
    build:
      context: ./api
    ports:
      - 4000:4000
      - 9229:9229 # Debugger
    volumes:
      - ./api:/app

  web:
    build:
      context: ./web
    ports:
      - 3000:3000
    volumes:
      - ./web:/app
